os:
  - linux
dist: bionic
language: python
python:
  - "3.7"

env:
  - TRAVIS: true

services:
- docker

if: (type == push)

script:
  - sleep 3

after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- pip install python-semantic-release==7.15.0
- semantic-release publish -v DEBUG
